name: top_zone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  google_maps_flutter: ^2.0.8
  geolocator: ^7.6.0
  dio: ^3.0.1
  pinput: ^1.2.0
  file_picker: ^4.0.1
  retrofit: 1.3.4+1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.5
  multi_image_picker: ^4.8.0
  flutter_absolute_path: ^1.0.6
  image_picker:
  geocoding: ^2.0.1
  flutter_svg_provider: ^0.1.10
  cached_network_image: ^2.5.1
  lottie: ^1.1.0
  smooth_star_rating: ^1.1.1
  flutter_spinkit: ^5.1.0
  flutter_html:
  url_launcher:
  flutter_datetime_picker: 1.5.0
  flutter_image_compress:
  image_cropper:

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: taj
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 700
        
